trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'test-api'  # Replace with your image name
  containerRegistry: 'test-api-container.azurecr.io'  # Replace with your Azure Container Registry name
  containerRegistryUsername: '$(acrUsername)'  # Set these as pipeline secrets
  containerRegistryPassword: '$(acrPassword)'
  azureSubscription: '$(azureSubscription)'
  resource-group: '$(resource-group)'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: 'latest'
  displayName: 'Install Docker'

- script: |
    docker login $(containerRegistry) -u $(containerRegistryUsername) -p $(containerRegistryPassword)
  displayName: 'Docker Login to ACR'

- script: |
    docker build -t $(containerRegistry)/$(imageName):$(Build.BuildId) ml-project
  displayName: 'Build Docker Image'

- script: |
    docker push $(containerRegistry)/$(imageName):$(Build.BuildId)
  displayName: 'Push Docker Image to ACR'

- task: AzureCLI@2
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az container create \
        --resource-group $(resource-group) \
        --name test-api-container-instance \
        --image $(containerRegistry)/$(imageName):$(Build.BuildId) \
        --registry-login-server $(containerRegistry) \
        --registry-username $(containerRegistryUsername) \
        --registry-password $(containerRegistryPassword) \
        --ports 8000
  displayName: 'Deploy to Azure Container Instance'

