trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  RESOURCE_GROUP: 'dmc-group'
  ACR_NAME: 'testcontainerdmc'
  REPOSITORY_NAME: 'my-test-api'
  IMAGE_TAG: 'latest'
  AZURE_SUBSCRIPTION_ID: '37520400-632e-413e-b571-e52d252eb3c6'
  AZURE_SERVICE_CONNECTION: 'azure-devops-connection'

steps:
- task: AzureCLI@2
  displayName: 'Setup and Deploy'
  inputs:
    azureSubscription: '$(AZURE_SERVICE_CONNECTION)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account set --subscription '$(AZURE_SUBSCRIPTION_ID)'
      az acr show --name $(ACR_NAME) --resource-group $(RESOURCE_GROUP) || \
      az acr create --resource-group $(RESOURCE_GROUP) --name $(ACR_NAME) --sku Basic
      docker build -t $(ACR_NAME).azurecr.io/$(REPOSITORY_NAME):$(IMAGE_TAG) -f Dockerfile .
      docker push $(ACR_NAME).azurecr.io/$(REPOSITORY_NAME):$(IMAGE_TAG)
      az container create \
        --resource-group $(RESOURCE_GROUP) \
        --name $(REPOSITORY_NAME)-container \
        --image $(ACR_NAME).azurecr.io/$(REPOSITORY_NAME):$(IMAGE_TAG) \
        --cpu 1 \
        --memory 1 \
        --registry-login-server $(ACR_NAME).azurecr.io \
        --registry-username $(az acr credential show --name $(ACR_NAME) --query username -o tsv) \
        --registry-password $(az acr credential show --name $(ACR_NAME) --query passwords[0].value -o tsv)

